version: '3.8'

services:
  backend:
    build: ./backend
    container_name: task-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/taskmanager
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: task-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: task-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local